###
POST http://127.0.0.1:3000/user/sign-up-user HTTP/1.1
Content-Type: application/json

{
   "email": "fboudhraa2@gmail.com",
   "userName": "firas",
   "password": "firas20101995",
   "Age": 28,
   "tel": 28107403,
   "adress": "manouba rue syrie"
}

###
POST http://127.0.0.1:3000/user/sign-in-user HTTP/1.1
Content-Type: application/json

{
   "email": "fboudhraa2@gmail.com",
   "password": "firas20101995"
}

###
POST http://127.0.0.1:3000/user/update-user HTTP/1.1
Content-Type: application/json

{
   "email": "fboudhraa2@gmail.com",
   "userName": "firas",
   "password": "firas20101995",
   "Age": 28,
   "tel": 28107403,
   "adress": "manouba rue syrie"
}

