const ERROR_CODES = {
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    NOT_FOUND: "NOT_FOUND",
    UNAUTHENTICATED: "UNAUTHENTICATED",
    UNAUTHORIZED: "UNAUTHORIZED",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
  };
  
  module.exports = { ERROR_CODES };